[package]
name = "sylt-compiler"
description = """
Compiler for the Sylt programming language.
"""
license = "MIT"
repository = "https://github.com/FredTheDino/sylt.git"
readme = "../README.md"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/compiler.rs"

[dependencies]
sylt-common = { version = "0.1.0", path = "../sylt-common" }
sylt-parser = { version = "0.1.0", path = "../sylt-parser" }
